accounts/urls.py
from django.urls import path
from . import views

app_name = 'profile'
urlpatterns = [
    path('settings/', views.settings, name='settings'),
    path('history/', views.history, name='history'),
]

api/urls.py
from django.urls import path
from . import views

app_name = 'api'
urlpatterns = [
    path('movies/', views.movie_api, name="movie_api"),
    path('title=<slug>/', views.movie_api_slug, name='movie_api_slug'),
    path('search_movie/', views.search_movie, name='search_movie'),
]

cinema_core/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from random import random

app_name = 'cinema'

def generate_random():
    random_number = str(random())
    random_number = random_number.replace(".", "")
    return random_number

urlpatterns = [
    path('', views.index, name='index'),
    path('book-ticket/', views.book_ticket, name='book_ticket'),
    path('buy-ticket/<slug>/', views.buy_ticket, name='buy_ticket'),
    path('ticket-view/<slug>/', views.ticket_view, name='ticket_view'),
    path('snacks/', views.snacks, name='snacks'),
    
    path('user-select/<int:movie_id>&id=<int:seat_id>/', views._user_select, name='user_select'),
    # path('user-select/{}<int:movie_id>{}?id={}<int:seat_id>{}/'.format(
    #     generate_random()[1:], generate_random(),
    #     generate_random(), generate_random()
    # ), views._user_select, name='user_select'),

    path('search/', views.search_movie, name='search_movie'),
    path('redirect_now_showing/', views.redirect_now_showing, name='redirect_now_showing'),
    path('redirect_coming_soon/', views.redirect_coming_soon, name='redirect_coming_soon'),
    

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cinema_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('cinema_core.urls')),
    path('admin-panel/', admin.site.urls),
    path('profile/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('manager/', include('like_manager.urls')),
    path('api/', include('api.urls')),
    path('payment/', include('payment.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class History(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.CharField(max_length=150)
    theater = models.CharField(max_length=100)
    price = models.IntegerField()
    seat = models.CharField(max_length=50)
    time = models.CharField(max_length=100)
    date = models.CharField(max_length=150)

    def __str__(self):
        return "{} - {}".format(self.user, self.movie)

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
from django.contrib.auth.decorators import login_required
from .models import History

@login_required
def settings(request):
    return render(request, 'profile/settings.html')

@login_required
def history(request):
    history = History.objects.filter(user=request.user)
    context = {'history': history}
    return render(request, 'profile/history.html', context)

accounts/templates/profile/history.html
{% extends 'cinema/base.html' %}
{% load static %}
{% block title %}History{% endblock title %}

{% block style %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">
{% endblock style %}
{% block script %}

    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>

{% endblock script %}
{% block content %}
    <div class="container">
        <div class="pb-2 pt-2 mb-3 border-bottom">
            <h3>History</h3>
        </div>
        <table id="history" class="table table-striped dt-responsive">
            <thead class="bg-dark text-white">
                <tr>
                  <th scope="col">Movie</th>
                  <th scope="col">Date</th>
                  <th scope="col">Seat</th>
                  <th scope="col">Price</th>
                </tr>
              </thead>
              <tbody>
                {% for history in history %}
                    <tr>
                        <th>{{ history.movie }}</th>
                        <td>
                            <p><b>{{ history.theater }}</b></p>
                            <p>{{ history.date }}</p>
                            <p>{{ history.time }}</p>
                        </td>
                        <td>{{ history.seat }}</td>
                        <td>₱{{ history.price }}</td>
                    </tr>
                {% empty %}
                    <div class="alert alert-info" role="alert">
                        History is empty.
                    </div>
                {% endfor %}
              </tbody>
        </table>
    </div>
{% endblock content %}
{% block bottom_script %}
    <script src="{% static 'accounts/script/history.js' %}"></script>
{% endblock bottom_script %}

accounts/templates/profile/settings.html
{% extends 'cinema/base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block title %}Settings{% endblock title%}

{% block content %}
    <div class="container">
        <div class="pb-2 pt-2 mb-4 mt-3 border-bottom">
            <h3>Settings</h3>
        </div>
        <div class="card mb-3">
            <div class="card-body">
                <ul class="list-group">
                    <a href="{% url 'account_email' %}" style="text-decoration:none">
                        <li class="list-group-item">
                            <div class="row mt-3 mb-2">
                                <div class="col-sm">
                                    <h5 class="text-dark">Email Addresses</h5>
                                </div>
                                <div class="col-xl">
                                    <h5 class="text-secondary">{{ user.email}}</h5>
                                </div>
                                <div class="col">
                                    <h5 id="edit_email" class="text-primary float-right">Edit</h5>
                                </div>
                            </div>
                        </li>
                    </a>
                    <a href="{% url 'account_change_password' %}" style="text-decoration:none">
                        <li class="list-group-item">
                            <div class="row mt-3 mb-2">
                                <div class="col-sm">
                                    <h5 class="text-dark">Password</h5>
                                </div>
                                <div class="col-xl">
                                    <h5 class="text-secondary">****************</h5>
                                </div>
                                <div class="col">
                                    <h5 id="edit_pass" class="text-primary float-right">Edit</h5>
                                </div>
                            </div>
                        </li>
                    </a>
                </ul>    
            </div>
          </div>
          <a href="{% url 'api:movie_api' %}" class="btn btn-primary float-right ml-2">View API</a>
          <a href="{% url 'cinema:index' %}" class="btn btn-primary float-right">Cancel</a>
    </div>
{% endblock content %}
{% block bottom_script%}
<script src="{% static 'accounts/script/settings.js' %}"></script>
{% endblock bottom_script %}