accounts/urls.py
from django.urls import path
from . import views

app_name = 'profile'
urlpatterns = [
    path('settings/', views.settings, name='settings'),
    path('history/', views.history, name='history'),
]

api/urls.py
from django.urls import path
from . import views

app_name = 'api'
urlpatterns = [
    path('movies/', views.movie_api, name="movie_api"),
    path('title=<slug>/', views.movie_api_slug, name='movie_api_slug'),
    path('search_movie/', views.search_movie, name='search_movie'),
]

cinema_core/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from random import random

app_name = 'cinema'

def generate_random():
    random_number = str(random())
    random_number = random_number.replace(".", "")
    return random_number

urlpatterns = [
    path('', views.index, name='index'),
    path('book-ticket/', views.book_ticket, name='book_ticket'),
    path('buy-ticket/<slug>/', views.buy_ticket, name='buy_ticket'),
    path('ticket-view/<slug>/', views.ticket_view, name='ticket_view'),
    path('snacks/', views.snacks, name='snacks'),
    
    path('user-select/<int:movie_id>&id=<int:seat_id>/', views._user_select, name='user_select'),
    # path('user-select/{}<int:movie_id>{}?id={}<int:seat_id>{}/'.format(
    #     generate_random()[1:], generate_random(),
    #     generate_random(), generate_random()
    # ), views._user_select, name='user_select'),

    path('search/', views.search_movie, name='search_movie'),
    path('redirect_now_showing/', views.redirect_now_showing, name='redirect_now_showing'),
    path('redirect_coming_soon/', views.redirect_coming_soon, name='redirect_coming_soon'),
    

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cinema_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('cinema_core.urls')),
    path('admin-panel/', admin.site.urls),
    path('profile/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('manager/', include('like_manager.urls')),
    path('api/', include('api.urls')),
    path('payment/', include('payment.urls')),
]

like_manager/urls.py
from django.urls import path
from . import views

app_name = 'manager'
urlpatterns = [
    path('like/<slug>/', views.like, name='like'),
    path('dislike/<slug>/', views.dislike, name='dislike'),
]

cinema_core/models.py
from django.db import models
from django.core.exceptions import ValidationError
from datetime import date, datetime, time, timedelta
from django.template.defaultfilters import slugify

# Create your models here.

class OperationTime(models.Model):
    opening = models.TimeField()
    closing = models.TimeField()

    def __str__(self):
        return "{} to {}".format(self.opening, self.closing)

class Theater(models.Model):
    theater = models.CharField(max_length=10, unique=True)
    capacity = models.IntegerField(default=5)
    limit_per_day = models.IntegerField(default=4)
    operation_time = models.ForeignKey(OperationTime, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.theater

class Genre(models.Model):
    genre = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.genre

class Movie(models.Model):
    theater = models.OneToOneField(Theater, on_delete=models.CASCADE)
    movie_title = models.CharField(max_length=150, unique=True)
    movie_price = models.IntegerField()
    movie_length = models.DurationField()
    movie_genre = models.ManyToManyField(Genre)
    movie_banner = models.ImageField(upload_to='movie_banner')
    movie_description = models.TextField()
    directors = models.TextField()
    screen_play = models.TextField()

    movie_link = models.URLField()
    start_date = models.DateField()
    end_date = models.DateField()
    slug = models.SlugField(max_length=250, allow_unicode=True, blank=True, default="Automated")

    def _create_schedule(self):
        theater_start = self.theater.operation_time.opening
        theater_end = self.theater.operation_time.closing
        movie_break = 30 # in minutes

        movie_duration = self.movie_length.total_seconds()
        hours = int(movie_duration // 3600)
        minutes = int((movie_duration % 3600) // 60)

        theater_hour = theater_start.hour + hours
        theater_minute = theater_start.minute + minutes
        current = theater_start.replace(hour=theater_hour, minute=theater_minute)

        for limit in range(self.theater.limit_per_day):
                schedule = Schedule.objects.update_or_create(
                    movie=self,
                    start_time=theater_start,
                    end_time=current,
                )
                current_hour = current.hour
                current_minute = current.minute
                total_minute = current_minute + movie_break

                if total_minute < 60:
                    theater_start = current.replace(minute=current_minute+movie_break)
                else:
                    calculate_minute = total_minute - 60
                    theater_start = current.replace(hour=current_hour+1, minute=calculate_minute)
                
                temp = theater_start
                calculate_hour = temp.hour + hours
                if calculate_hour < theater_end.hour:
                    current = temp.replace(hour=calculate_hour, minute=temp.minute+minutes)
                else:
                    break

    def _create_seats(self):
        start_date = self.start_date
        end_date = self.end_date
        span = end_date - start_date

        seat_row_range = 10
        seat_label = [chr(letter) for letter in range(65, 91)]
        seat_col_range = self.theater.capacity // seat_row_range
    
        for day in range(span.days + 1):
            date_display = start_date + timedelta(days=day)
            for time in Schedule.objects.filter(movie=self):
                row_track = 0
                col_track = 0
                for capacity in range(self.theater.capacity):
                    row_track += 1
                    
                    if row_track > seat_row_range:
                        row_track = 1
                        if col_track < seat_col_range:
                            col_track += 1

                    display = "{}-{}".format(seat_label[col_track], row_track)

                    if not date_display < date.today():
                        cinema_seat = CinemaSeat.objects.update_or_create(
                            movie=self,
                            theater=self.theater, 
                            seat=display, 
                            time=time,
                            date=date_display.strftime('%B %d, %Y - %A'),
                            time_char_field=str(time),
                            actual_date=date_display,
                        )

    def clean(self):    
        if self.start_date > self.end_date:
            raise ValidationError("- Dates are incorrect!")
    
    def __str__(self):
        return self.movie_title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.movie_title)
        # https://youtu.be/ybji16u608U - url
        # Please copy the actual url by right clicking on youtube videos
        
        url_link = self.movie_link.rindex('/') + 1
        code_link = self.movie_link[url_link:]
        generated_link = "https://youtube.com/embed/" + code_link
        self.movie_link = generated_link

        if len(self.movie_description) > 350:
            self.movie_description = self.movie_description[:350]

        super(Movie, self).save(*args, **kwargs)
        self._create_schedule()
        self._create_seats()

class Schedule(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, db_constraint=False)
    start_time = models.TimeField()
    end_time = models.TimeField()

    def __str__(self):
        start_time = self.start_time.strftime("%I:%M %p")
        end_time = self.end_time.strftime("%I:%M %p")
        
        return "{} to {}".format(start_time, end_time)

class CinemaSeat(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, db_constraint=False)
    theater = models.ForeignKey(Theater, on_delete=models.CASCADE)
    seat = models.CharField(max_length=5)
    time = models.ForeignKey(Schedule, on_delete=models.CASCADE, editable=False)
    date = models.CharField(max_length=150, editable=False)
    paid = models.BooleanField(default=True)
    time_char_field = models.CharField(max_length=150, default=None, editable=False)
    actual_date = models.DateField()


    def __str__(self):
        return "{} | {} | {} - {}".format(
                self.theater, self.seat, 
                self.time, self.date
            )

cinema_core/views.py
import stripe
from django.shortcuts import render, redirect, reverse
from .models import Movie, Schedule, CinemaSeat
from like_manager.models import Like, Dislike
from django.shortcuts import get_object_or_404, get_list_or_404
from datetime import date, datetime, timedelta
from django.forms.models import model_to_dict
from django.http import JsonResponse, request
from django.contrib.auth.decorators import login_required

# Create your views here.
current_date = date.today()
current_time = datetime.utcnow().time()

def _get_movies():
    _movies = Movie.objects.all()
    movies = list()
    coming_soon = list()

    for movie in _movies:
        if current_date >= movie.start_date and current_date <= movie.end_date:
            movies.append(Movie.objects.get(movie_title=movie.movie_title))

        if movie.start_date > current_date:
            coming_soon.append(Movie.objects.get(movie_title=movie.movie_title))

    context = {
        'movies': movies,
        'coming_soon': coming_soon,
    }

    return context

def _calculate_duration(movie_length):
    duration = movie_length
    total_seconds = int(duration.total_seconds())
    total_minutes = total_seconds // 60
    
    return total_minutes

def _movies(description_length=150):
    movies = _get_movies()

    for movie in movies['movies']:
        movie.movie_length = "{} Minutes".format(_calculate_duration(movie.movie_length))

        if len(movie.movie_description) >= description_length:
            movie.movie_description = movie.movie_description[:description_length] + "..."

        if len(movie.movie_description) == description_length:
            movie.movie_description += movie.movie_description +  "..."

    for movie in movies['coming_soon']:
        movie.movie_length = "{} Minutes".format(_calculate_duration(movie.movie_length))

        if len(movie.movie_description) >= description_length:
            movie.movie_description = movie.movie_description[:description_length] + "..."

        if len(movie.movie_description) == description_length:
            movie.movie_description += movie.movie_description +  "..."

    return movies

@login_required
def _calculate_order(request):
    total_amount = 0
    ticket_orders = list()
    serialized = list()

    for key, value in request.session.items():
        if key == str(value):
            cinema = CinemaSeat.objects.get(id=value)
            cinema_dict = model_to_dict(cinema)
            cinema_dict['movie_title'] = cinema.movie.movie_title
            cinema_dict['movie_price'] = cinema.movie.movie_price
            cinema_dict['date'] = str(cinema.date)
            cinema_dict['time'] = str(cinema.time)
            cinema_dict['movie_banner'] = str(cinema.movie.movie_banner.url)
            cinema_dict['theater_name'] = str(cinema.movie.theater)
            serialized.append(cinema_dict)
            ticket_orders.append(cinema)
            total_amount += cinema.movie.movie_price
    
    return {
        'total_amount': total_amount, 
        'ticket_orders': ticket_orders,
        'serialized': serialized,
    }    

@login_required
def _user_select(request, movie_id, seat_id):
    try:
        if request.is_ajax():
            seat = str(seat_id)
            if seat not in request.session:
                request.session[seat] = seat_id
            else:
                request.session.pop(seat)
    except KeyError:
        pass
    
    else:
        orders = _calculate_order(request)
        context = {
            'ticket_orders': orders['serialized'],
            'total_amount': orders['total_amount'],
            'cart': len(orders['serialized']),
        }   

        return JsonResponse(context, safe=False, status=200, json_dumps_params={'indent': 4})

def _calculate_like():
    movies = Movie.objects.all()
    like_dict = {}
    dislike_dict = {}
    total_dict = {}

    for movie in movies:
        if current_date >= movie.start_date and current_date <= movie.end_date:
            like_dict["{}".format(movie)] = len(Like.objects.filter(movie=movie.id))
            dislike_dict["{}".format(movie)] = len(Dislike.objects.filter(movie=movie.id))

        if movie.start_date > current_date:
            like_dict["{}".format(movie)] = len(Like.objects.filter(movie=movie.id))
            dislike_dict["{}".format(movie)] = len(Dislike.objects.filter(movie=movie.id))

    for like_key, like_val in like_dict.items():
        for dislike_key, dislike_val in dislike_dict.items():
            if like_key == dislike_key:
                if like_val != 0 or dislike_val != 0:
                    total_dict["{}".format(like_key)] = int((like_val/(like_val + dislike_val)) * 100)
                elif like_val == 0 and dislike_val == 0:
                    total_dict["{}".format(like_key)] = 0

    return total_dict

def index(request):
    movies = _movies(350)
    total_dict = _calculate_like()
    top_movies = {movie: total_count for movie, total_count in sorted(total_dict.items(), key=lambda total: total[1], reverse=True)}

    context = {
        'movies': movies['movies'], 
        'total_dict':total_dict,
        'top_movies': top_movies,
        'coming_soon': movies['coming_soon'],
    }

    if request.user.is_authenticated:
        likes = Like.objects.filter(user=request.user)
        dislikes = Dislike.objects.filter(user=request.user)
        like_movie = [like.movie for like in likes]
        dislike_movie = [dislike.movie for dislike in dislikes]

        context['like_movie'] = like_movie
        context['dislike_movie'] = dislike_movie
    
    return render(request, 'cinema/index.html', context)

def book_ticket(request):
    movies = _movies(150)
    context = {'movies': movies['movies']}
    return render(request, 'cinema/book_ticket.html', context)

def buy_ticket(request, slug):
    day_spans = list()
    total_dict = _calculate_like()
    movie = get_object_or_404(Movie, slug=slug)
    movie.movie_length = "{} Minutes".format(_calculate_duration(movie.movie_length))
    theater_times = Schedule.objects.filter(movie=movie)

    span = movie.end_date - current_date
    for day in range(span.days + 1):
        days = current_date + timedelta(days=day)
        day_spans.append(days.strftime('%B %d, %Y - %A'))

    context = {
        'movie': movie,
        'day_spans': day_spans,
        'theater_times': theater_times,
        'total_dict': total_dict,
    }

    if request.user.is_authenticated:
        likes = Like.objects.filter(user=request.user)
        dislikes = Dislike.objects.filter(user=request.user)
        like_movie = [like.movie for like in likes]
        dislike_movie = [dislike.movie for dislike in dislikes]

        context['like_movie'] = like_movie
        context['dislike_movie'] = dislike_movie

    return render(request, 'cinema/buy_ticket.html', context)

@login_required
def ticket_view(request, slug):
    movies = get_object_or_404(Movie, slug=slug)

    if request.method == "POST":
        request.session['theater_time'] = request.POST['theater_time']
        request.session['theater_date'] = request.POST['theater_date']

    cinema_seats = CinemaSeat.objects.filter(
        theater=movies.theater, 
        time_char_field=request.session.get('theater_time'),
        date=request.session.get('theater_date'),
    ).order_by('id')

    orders = _calculate_order(request)
    context = {
        'movies': movies,
        'cinema_seats': cinema_seats,
        'theater_time': request.session.get('theater_time'),
        'theater_date': request.session.get('theater_date'),
        'ticket_orders': orders['ticket_orders'],
        'total_amount': orders['total_amount'],
        'cart': len(orders['ticket_orders']),
    }   

    if request.session.get('theater_time') and request.session.get('theater_date'):
        return render(request, 'cinema/ticket_view.html', context)
    else:
        return redirect('cinema:book_ticket')

def snacks(request):
    return render(request, 'cinema/snacks.html', )


def search_movie(request):
    if request.method == "POST":
        try:
            movie = Movie.objects.get(movie_title__icontains=request.POST['search'])
       
        except Movie.DoesNotExist:  
            return render(request, 'cinema/search.html')

        else:
            return redirect('cinema:buy_ticket', slug=movie.slug)            

def redirect_now_showing(request):
    return redirect(reverse('cinema:index') + "#now_showing_section")

def redirect_coming_soon(request):
    return redirect(reverse('cinema:index') + "#coming_soon_section")

cinema_core/templates/cinema/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title%}</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" type="text/css" href="{% static 'cinema_core/css/navigation.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'cinema_core/css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'cinema_core/css/movieSection.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@v2.3.5/dist/latest/bootstrap-autocomplete.min.js"></script>
    {% block script %}{% endblock script %}
    {% block style %}{% endblock style %}
</head>

<body class="d-flex flex-column min-vh-100">
    <nav class="navbar sticky-top navbar-light bg-light navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="{% url 'cinema:index' %}"><h3>Cinema</h3></a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" 
                    data-target="#navbarCollapse" aria-controls="navbarCollapse" 
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
            </button>
            <form method="POST" action="{% url 'cinema:search_movie' %}" class="form-inline">
                    {% csrf_token %}
                    <input class="form-control searchMovie mr-sm-2" type="text" name="search" placeholder="Search Movie" autocomplete="off">
                    <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Go</button>
            </form> 
                
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto mr-5">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="" id="navBarDropDown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">MOVIES</a>
                    
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'cinema:redirect_now_showing' %}">Now Showing</a>
                        <a class="dropdown-item" id="coming_soon_dropdown" href="{% url 'cinema:redirect_coming_soon' %}">Coming Soon</a>
                    </div>
                    </li>

                    <li class="nav-item"><a class="nav-link" href="{% url 'cinema:snacks' %}">SNACKS</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'cinema:book_ticket' %}">BOOK TICKET</a></li>
                </ul>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="" id="navBarDropDownProfile" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">PROFILE</a>
                    
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownProfile">
                                <a href="{% url 'profile:history' %}" class="dropdown-item" href="">History</a>
                                <a class="dropdown-item" href="{% url 'profile:settings' %}">Settings</a>
                                <a href="{% url 'account_logout' %}" class="dropdown-item" href="">Logout</a>
                                
                            </div>
                        </li>
                    {% else %}
                        <li class="nav-item"><a href="{% url 'account_login' %}" id="btnCollapse" type="button" class="btn btn-dark" href="">SIGN IN</a></li>
                        <li class="nav-item"><a href="{% url 'account_login' %}" id="btnShow" class="nav-link" href="">SIGN IN</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
        
    </nav>
    <div class="wrapper flex-grow-1">
        <main role="main">
            {% block content %}{% endblock content %}
        </main>
    </div>
    <!-- Footer -->
    <footer class="page-footer font-small bg-dark mt-5">
        <div class="container text-center text-md-left">
            <div class="row mt-3">
                <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4 text-white mt-5">
                    <h6 class="text-uppercase font-weight-bold">Cinema</h6>
                    <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
                    <p>Enjoy the latest international & local films with your family & friends at Cinema!</p>
                </div>

                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4 text-white mt-5">
                    <h6 class="text-uppercase font-weight-bold">Contact</h6>
                    <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
                    <p class="text-white">+63123123123</p>
                    <p class="text-white">cinema@cinema.com</p>
                </div>
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4 text-white mt-5">
                    <h6 class="text-uppercase font-weight-bold">Developers</h6>
                    <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
                    <p><a class="text-white" href="{% url 'api:movie_api' %}">Movies API</a></p>
                </div>
            </div>
        </div>

        <div class="footer-copyright text-center py-3 bg-secondary">© 2020 Copyright:
            <a class="text-white" href="#"> cinema.com</a>
        </div>
    </footer>
    <!-- End Footer -->
    {% block bottom_script %}{% endblock bottom_script %}
    <script>
        $('.searchMovie').autoComplete({
            resolverSettings: {
                url: '{% url "api:search_movie" %}'
            }
        });
    </script>
</body>
</html>

cinema_core/templates/cinema/book_ticket.html
{% extends 'cinema/base.html' %}
{% load static %}
{% block title %}Book Ticket{% endblock title %}
{% block style %}

{% endblock style %}
{% block content %}
    <div class="container">
        <div class="pb-2 pt-2 mb-3 border-bottom">
            <h3>Book Ticket</h3>
        </div>
        <div class="d-flex flex-row flex-wrap">
            {% for movie in movies %}
                <div class="card mb-2 ml-auto mr-auto" style="width: 34.5rem">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                            <img class="card-img" src="{{ movie.movie_banner.url }}">
                        </div>
    
                        <div class="col-md-8">
                            <div class="card-body">
                                <h3 class="card-title">{{ movie.movie_title }}</h3>
                                <p class="card-text"><b>Run Time: {{ movie.movie_length }}</b></p>
                                <div style="height: 5.5rem;">
                                    <p class="text-justify">{{ movie.movie_description }}...</p>
                                </div>
                            </div>
    
                            <div class="card-footer">
                                <a class="btn btn-primary" href="{% url 'cinema:buy_ticket' movie.slug %}">Buy Tickets</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% empty %}
                <div class="alert alert-info" role="alert">
                        No available movies at the moment.
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

cinema_core/templates/cinema/buy_ticket.html
{% extends 'cinema/base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block title %}Buy Ticket{% endblock title %}
{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'cinema_core/css/buy_ticket_jumbotron.css' %}">
{% endblock style %}
{% block script %}
    <script src="{% static 'cinema_core/script/buy_ticket.js' %}"></script>
{% endblock script %}
{% block content %}
    <div class="container">
        <div class="jumbotron jumbotron-fluid"></div>
        <div class="row">
            <div class="col">
                <div class="row">
                    <img id="image_banner" src="{{ movie.movie_banner.url }}" class="w-25 ml-5" style="margin-top: -10%">
                    <div id="like_manager" class="ml-4">
                        <h3 class="card-title">{{ movie.movie_title }}</h3>
                        <p class="card-text"><b>Genre: 
                            {% for genre in movie.movie_genre.all %}
                                {% if movie.movie_genre.all|length > 1 %}
                                    {% if forloop.counter == movie.movie_genre.all|length %}
                                        {{genre}}
                                    {% else %}
                                        {{genre}} / 
                                    {% endif %}
                                {% else %}
                                    {{genre}}
                                {% endif %}
                            {% endfor %}
                        </b></p>
                        <p class="card-text"><b>Run Time: {{ movie.movie_length }}</b></p>                 
                        <p class="card-text"><b>Directors:</b> {{movie.directors}}</p>
                        <p class="card-text text-muted">
                            {% for movie_, total in total_dict.items %}
                                {% if movie_ == movie.movie_title %}
                                    {% if total != 0%}
                                        {{total}}% Liked this film.
                                    {% else %}
                                        No one likes yet.
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                           
                            {% if movie in like_movie %}
                                <a id="like" data-manager="{{movie.slug}}" href="{% url 'manager:like' movie.slug %}"><i data-like="{{movie.slug}}" class="fa fa-thumbs-up fa-2x text-primary ml-3 mr-3"></i></a>
                            {% else %}
                                <a id="like" data-manager="{{movie.slug}}" href="{% url 'manager:like' movie.slug %}"><i data-like="{{movie.slug}}" class="fa fa-thumbs-up fa-2x text-dark ml-3 mr-3"></i></a>
                            {% endif %}
                            {% if movie in dislike_movie %}
                                <a id="dislike" data-manager="{{movie.slug}}" href="{% url 'manager:dislike' movie.slug %}"><i data-dislike="{{movie.slug}}" class="fa fa-thumbs-down fa-2x text-primary mr-5"></i></a>
                                {% else %}
                                <a id="dislike" data-manager="{{movie.slug}}" href="{% url 'manager:dislike' movie.slug %}"><i data-dislike="{{movie.slug}}" class="fa fa-thumbs-down fa-2x text-dark mr-5"></i></a>
                            {% endif %}
     
                        </p>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#{{movie.slug}}">Play Trailer</button>
                    </div>
                </div>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="{{movie.slug}}" tabindex="-1" role="dialog" aria-labelledby="viewTrailerLabel" aria-hidden="true">
                <div class="modal-dialog modal-xl" role="document">
                    <div class="modal-content bg-transparent border-0">
                        <div class="modal-body">
                            <div class="embed-responsive embed-responsive-16by9">
                                <iframe class="embed-responsive-item" src="{{ movie.movie_link }}" allowfullscreen></iframe>
                            </div>
                        </div>
                    </div>
                </div>
            </div>                  
            <!-- End -->
        </div>
        <hr>
        <div id="container_form" class="container mt-3 ml-3 mb-5">
            <p class="card-text"><b>Screenplay:</b> {{movie.screen_play}}</p>
            <p class="text-justify">{{ movie.movie_description }}</p>

            <form method="POST" action="{% url 'cinema:ticket_view' movie.slug %}">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col">
                        <label class="float-left mt-2 mb-n2"><h5>Price: ₱{{ movie.movie_price }}</h5></label>
                    </div>
                    <div class="form-group col-md-4">
                        <select class="custom-select" name="theater_time">
                            {% for theater_time in theater_times %}
                                <option value="{{ theater_time }}">{{ theater_time }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group col-md-4">
                        <select class="custom-select" name="theater_date">
                            {% for day_span in day_spans %}
                                <option value="{{ day_span }}">{{ day_span }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    
                    {% buttons %}
                        <button class="btn btn-primary" name="submit">View Seats</button>
                    {% endbuttons %}
                </div>
            </form>
        </div>
    </div>
{% endblock content %}
{% block bottom_script %}
    <script src="{% static 'cinema_core/script/like_manager.js' %}"></script>
{% endblock bottom_script %}