accounts/urls.py
from django.urls import path
from . import views

app_name = 'profile'
urlpatterns = [
    path('settings/', views.settings, name='settings'),
    path('history/', views.history, name='history'),
]

api/urls.py
from django.urls import path
from . import views

app_name = 'api'
urlpatterns = [
    path('movies/', views.movie_api, name="movie_api"),
    path('title=<slug>/', views.movie_api_slug, name='movie_api_slug'),
    path('search_movie/', views.search_movie, name='search_movie'),
]

cinema_core/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from random import random

app_name = 'cinema'

def generate_random():
    random_number = str(random())
    random_number = random_number.replace(".", "")
    return random_number

urlpatterns = [
    path('', views.index, name='index'),
    path('book-ticket/', views.book_ticket, name='book_ticket'),
    path('buy-ticket/<slug>/', views.buy_ticket, name='buy_ticket'),
    path('ticket-view/<slug>/', views.ticket_view, name='ticket_view'),
    path('snacks/', views.snacks, name='snacks'),
    
    path('user-select/<int:movie_id>&id=<int:seat_id>/', views._user_select, name='user_select'),
    # path('user-select/{}<int:movie_id>{}?id={}<int:seat_id>{}/'.format(
    #     generate_random()[1:], generate_random(),
    #     generate_random(), generate_random()
    # ), views._user_select, name='user_select'),

    path('search/', views.search_movie, name='search_movie'),
    path('redirect_now_showing/', views.redirect_now_showing, name='redirect_now_showing'),
    path('redirect_coming_soon/', views.redirect_coming_soon, name='redirect_coming_soon'),
    

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cinema_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('cinema_core.urls')),
    path('admin-panel/', admin.site.urls),
    path('profile/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('manager/', include('like_manager.urls')),
    path('api/', include('api.urls')),
    path('payment/', include('payment.urls')),
]

payment/urls.py
from django.urls import path
from . import views 

app_name = 'payment'
urlpatterns = [
    path('payment/', views.payment, name='payment'),
    path('payment_success/', views.payment_success, name='payment_success'),
    path('payment_failed/', views.payment_failed, name='payment_failed'),
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
import stripe
from django.shortcuts import render
from django.conf import settings
from django.urls import reverse
from django.http import request
from cinema_core.views import _calculate_order
from django.contrib.auth.decorators import login_required
from urllib.error import HTTPError
from django.template.loader import render_to_string
from django.core.mail import send_mail, BadHeaderError
from cinema_core.models import CinemaSeat
from accounts.models import History
# Create your views here.

@login_required
def payment(request):
    orders = _calculate_order(request)
    context = dict()

    if orders['total_amount'] != 0:
        stripe.api_key = settings.STRIPE_SECRET_KEY
        session = stripe.checkout.Session.create(
            mode='payment',
            payment_method_types=['card'],    
            customer_email="{}".format(request.user.email),
            submit_type="book",
            line_items=[{
                'quantity': 1,
                'amount': orders['total_amount'] * 100,
                'currency': 'php',
                'description': "Enjoy the latest international & local films with your family & friends at Cinema!",
                'name': 'Total Amount',
                'images': ['https://i.imgur.com/XSQACIF.jpg'],
            }],
            success_url=request.build_absolute_uri(reverse('payment:payment_success')) + '?session_id={CHECKOUT_SESSION_ID}',
            cancel_url=request.build_absolute_uri(reverse('cinema:index')),
        )
        
        context = {
            'cart_orders': len(orders['ticket_orders']),
            'ticket_orders': orders['ticket_orders'],
            'total_amount': orders['total_amount'],
            'previous_url': request.META.get('HTTP_REFERER'),
        }

        context['session'] = session.id
        context['public_key'] = settings.STRIPE_PUBLIC_KEY

    return render(request, 'payment/payment.html', context)
    

@login_required
def payment_success(request):
    ticket_orders = list()
   
    for key, value in request.session.items():
        if key == str(value):
            ticket_orders.append(key)
            cinema_seat = CinemaSeat.objects.get(id=value)
            cinema_seat.paid = False
            cinema_seat.save()

            history = History.objects.create(
                user=request.user,
                movie=cinema_seat.movie,
                theater=cinema_seat.theater,
                price=cinema_seat.movie.movie_price,
                seat=cinema_seat.seat,
                time=cinema_seat.time,
                date=cinema_seat.date,
            )

    if len(ticket_orders):
        orders = _calculate_order(request)
        subject = "Ticket Receipt"
        message = "Cinema ticket info"
        recipient_list = [request.user.email]
        html_message = render_to_string(
            'email/ticket_receipt.html', 
            context = {
                'cart_orders': len(orders['ticket_orders']),
                'ticket_orders': orders['ticket_orders'],
                'total_amount': orders['total_amount'],
            }
        )
        try:
            ticket_receipt = send_mail(
                subject = subject,
                message = message,
                from_email = settings.DEFAULT_FROM_EMAIL,
                recipient_list = recipient_list,
                fail_silently = True,
                html_message = html_message
            )

        except BadHeaderError:
            print("Error")

    for ticket in ticket_orders:
        request.session.pop(ticket)

    return render(request, 'payment/payment_success.html')

@login_required
def payment_failed(request):
    return render(request, 'payment/payment_failed.html')

payment/templates/payment/payment.html
{% extends 'cinema/base.html' %}
{% load static %}
{% block title %}Payment{% endblock title %}

{% block script %}
    <script src="{% static 'payment/script/mobile_payment.js' %}"></script>
{% endblock script %}
{% block content %}
    <div id="desktopView" class="container">
        <div class="card mt-5 shadow">
            <h5 class="card-header">Your orders
                {% if previous_url %}
                    <a href="{{ previous_url }}" class="h6 pt-1 text-muted float-right" style="text-decoration: none">Review ticket</a>
                {% else %}
                    <a href="{% url 'cinema:book_ticket' %}" class="h6 pt-1 text-muted float-right" style="text-decoration: none">Review ticket</a>
                {% endif %} 
            </h5>
            <div class="card-body">
                <ul class="list-group list-group-flush mb-3">
                    <li class="list-group-item active bg-dark">
                        <div class="row">
                            <div class="col">
                                Movie
                            </div>
                            <div class="col">
                                Date
                            </div>
                            <div class="col">
                                Seat No.
                            </div>
                            <div class="col">
                                Price
                            </div>
                        </div>
                    </li>
                    {% for ticket_order in ticket_orders %}
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col">
                                {{ ticket_order.movie.movie_title }}
                                </div>
                                <div class="col">
                                    <p class="card-text"><b>{{ ticket_order.movie.theater }}</b></p>
                                    <p class="card-text">{{ ticket_order.date }}</p>
                                    <p class="card-text">{{ ticket_order.time }}</p>
                                </div>
                                <div class="col">
                                    {{ ticket_order.seat }}
                                </div>
                                <div class="col">
                                    ₱ {{ ticket_order.movie.movie_price }}
                                </div>
                            </div>
                        </li>
                    {% empty %}
                        <li id="emptyCart" class="list-group-item d-flex justify-content-between lh-condensed">
                            <h6 class="mt-1">Please add a ticket</h6>
                        </li>
                    {% endfor %}

                  </ul>
                  <div class="continer float-right">
                    <div class="row mb-2">
                        {% if total_amount %}
                            <p class="card-text text-muted">Total Amount: ₱{{ total_amount }}</p>
                        {% endif %}
                    </div>
                    <div class="row mr-3">
                        {% if total_amount %}
                            <button id='checkout-button' data-secret="{{ session }}" class="btn btn-primary">Continue to checkout</button>
                        {% else %}
                            <a href="#" class="btn btn-primary disabled">Continue to checkout</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="mobileView" class="container">
        <div class="card mt-5 shadow">
            <h5 class="card-header">Your orders
                {% if previous_url %}
                    <a href="{{ previous_url }}" class="h6 pt-1 text-muted float-right" style="text-decoration: none">Review ticket</a>
                {% else %}
                    <a href="{% url 'cinema:book_ticket' %}" class="h6 pt-1 text-muted float-right" style="text-decoration: none">Review ticket</a>
                {% endif %} 
            </h5>
            <div class="card-body">
                <ul class="list-group mb-3 bg-white-rounded border-top-0 overflow-auto" id="ticketOrder">
                    {% for ticket_order in ticket_orders %}
                    <li data-order="{{ ticket_order.id }}" class="list-group-item d-flex justify-content-between lh-condensed">
                        <div>
                            <h6>{{ ticket_order.movie.movie_title}}</h6>
                            <h6><small class="text-muted">{{ ticket_order.date}}</small></h6>
                            <small class="text-muted">Seat No: {{ ticket_order.seat}}</small>
                        </div>
                        <div>
                        <span class="text-muted">₱{{ ticket_order.movie.movie_price }}</span>
                        </div>
                    </li>
                    {% empty %}
                        <li id="emptyCart" class="list-group-item d-flex justify-content-between lh-condensed">
                            <h6 class="mt-1">Please add a ticket</h6>
                        </li>
                    {% endfor %}
                </ul>
                <!-- Modal -->
                <div class="modal fade" id="view_ticket_info" tabindex="-1" role="dialog" aria-labelledby="viewTicketInfoLabel" aria-hidden="true">
                    <div class="modal-dialog modal-xl">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="viewTicketInfoLabel">Your Ticket Info</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body" id="modalBody">
                                {% for ticket_order in ticket_orders %}
                                    <div class="d-flex flex-row flex-wrap" data-modal="{{ ticket_order.id }}">
                                        <div id="card_block" class="card mb-2 ml-auto mr-auto" style="width: 34.5rem">
                                            <div class="row no-gutters">
                                                <div class="col-md-8">
                                                    <div class="card-body mb-3">
                                                        <h3 class="card-title">{{ ticket_order.movie }}</h3>
                                                        <p class="card-text"><b>{{ ticket_order.theater }} - Php {{ ticket_order.movie.movie_price }}</b></p>
                                                        <div style="height: 5.5rem;">
                                                            <p class="text-justify">{{ ticket_order.date }}</p>
                                                            <p class="test-justify">{{ ticket_order.time }}</p>
                                                            <p>Seat: <b>{{ ticket_order.seat }}</b></p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div> 
                                {% endfor %}
                            </div>
                            <button type="button" class="btn btn-dark rounded-0 float-right" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
                <!--  -->
                <div class="row float-left ml-0 mt-n2 mr-3">
                    <button id="view_ticket_card" type="button" data-toggle="modal" data-target="#view_ticket_info" class="btn btn-light btn-block">View Ticket Info</button>
                </div>
                <div class="continer float-right">
                    <div class="row mb-2">
                        {% if total_amount %}
                            <p id="total_amount_card" class="card-text text-muted">Total Amount: ₱{{ total_amount }}</p>
                        {% endif %}
                    </div>
                    <div class="row mr-3">
                        {% if total_amount %}
                            <button id='checkout-button-mobile' data-secret="{{ session }}" class="btn btn-primary">Continue to checkout</button>
                        {% else %}
                            <a href="#" class="btn btn-primary disabled">Continue to checkout</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block bottom_script %}
    <script src="https://js.stripe.com/v3/"></script>
    <script>
        var stripe = Stripe('{{ public_key }}');
        var session = '{{ session }}';
    </script>
    <script src="{% static 'payment/script/stripe.js' %}"></script>
{% endblock bottom_script %}

payment/templates/payment/payment_failed.html
{% extends 'cinema/base.html' %}
{% block title %}Payment Failed{% endblock title %}

{% block content %}
    <div class="container">
        <div class="pb-2 pt-2 mb-2 border-bottom">
            <h4>Payment Failed</h4>
        </div>
        <div class="alert alert-danger" role="alert">
            Your transaction is failed.
        </div>
        <div class="alert alert-danger" role="alert">
            Please add and review your tickets.
        </div>
        <a href="{% url 'cinema:book_ticket' %}" class="btn btn-primary float-right">Book Ticket</a>
    </div>
{% endblock content %}

payment/templates/payment/payment_success.html
{% extends 'cinema/base.html' %}
{% block title %}Payment Successful{% endblock title %}

{% block content %}
    <div class="container">
        <div class="pb-2 pt-2 mb-2 border-bottom">
            <h4>Payment Successful</h4>
        </div>
        <div class="alert alert-success" role="alert">
            You successfully booked the tickets.
        </div>
        <div class="alert alert-success" role="alert">
            Check your email for ticket receipts.
        </div>
        <a href="{% url 'cinema:book_ticket' %}" class="btn btn-primary float-right">Book Ticket</a>
        <a href="{% url 'profile:history' %}" class="btn btn-primary float-right mr-3">Check your History</a>
    </div>
{% endblock content %}